# AIDAS Protocol Configuration Example
# Copy this file to config.yaml and modify as needed

# Security Configuration
security:
  encryption_key_length: 32
  hash_algorithm: "sha256"
  aes_mode: "CBC"
  puf_noise_level: 0.03
  puf_verification_threshold: 0.9
  session_timeout_seconds: 3600
  max_authentication_attempts: 3
  enable_fuzzy_matching: true

# AI/ML Configuration
ai:
  dqn_state_dim: 10
  dqn_action_dim: 4
  dqn_memory_size: 10000
  learning_rate: 0.001
  epsilon_start: 1.0
  epsilon_min: 0.01
  epsilon_decay: 0.995
  gamma: 0.97
  batch_size: 32
  target_update_frequency: 100
  training_episodes: 1000

# Chaotic Map Configuration
chaotic_map:
  control_parameter: 3.99
  initial_condition_range: [0.1, 0.9]
  key_generation_iterations: 1000
  randomness_threshold: 0.45

# Network Configuration
network:
  esp_host: "localhost"
  esp_port: 8080
  api_version: "v1"
  timeout_seconds: 30
  max_retries: 3
  enable_tls: true
  cert_path: null
  key_path: null

# Database Configuration
database:
  db_type: "sqlite"
  db_host: "localhost"
  db_port: 5432
  db_name: "aidas"
  db_user: "aidas_user"
  db_password: ""
  db_path: "aidas.db"
  enable_migrations: true
  connection_pool_size: 10

# Logging Configuration
logging:
  log_level: "INFO"
  log_dir: "logs"
  enable_file_logging: true
  enable_console_logging: true
  enable_structured_logging: true
  max_log_file_size: "10MB"
  log_retention_days: 30

# Performance Configuration
performance:
  enable_caching: true
  cache_size: 1000
  cache_ttl_seconds: 300
  enable_metrics: true
  metrics_collection_interval: 60
  enable_profiling: false

# GUI Configuration
gui:
  theme: "light"
  window_width: 1200
  window_height: 800
  enable_animations: true
  refresh_rate: 1000
  chart_update_interval: 5000
